environment:
  avg_min: 36.0
  initial_prices:
  - 120.0
  - 115.0
  - 112.0
  - 119.0
  - 110.0
  max_rounds: 9
  num_bidders: 5
  possible_agents:
  - provider1
  - provider2
  - provider3
  - provider4
  - provider5
evaluation:
  num_games: 1
  render_mode: human
training:
  batch_size: 512
  ent_coef: 0.9
  learning_rate: 0.001
  seed: 42
  steps: 1800000
