environment:
  avg_min: 35.25
  initial_prices:
  - 120.0
  - 110.0
  - 118.0
  - 117.0
  max_rounds: 9
  num_bidders: 4
  possible_agents:
  - provider_1
  - provider_2
  - provider_3
  - provider_4
evaluation:
  num_games: 1
  render_mode: human
training:
  batch_size: 512
  ent_coef: 0.9
  learning_rate: 0.001
  seed: 42
  steps: 1800000
