environment:
  avg_min: 35.5
  initial_prices:
  - 120.0
  - 117.0
  - 110.0
  - 114.0
  max_rounds: 9
  num_bidders: 4
  possible_agents:
  - agent_1
  - agent_2
  - agent_3
  - agent_4
evaluation:
  num_games: 1
  render_mode: human
training:
  batch_size: 512
  ent_coef: 0.9
  learning_rate: 0.001
  seed: 42
  steps: 1800000
