environment:
  avg_min: 33.8
  initial_prices:
  - 120.0
  - 116.0
  - 117.0
  - 111.0
  - 118.0
  max_rounds: 10
  num_bidders: 5
  possible_agents:
  - string1
  - string2
  - string3
  - string4
  - string5
evaluation:
  num_games: 1
  render_mode: human
training:
  batch_size: 512
  ent_coef: 0.9
  learning_rate: 0.001
  seed: 42
  steps: 1800000
